### ISSUE TITLE
 Idea is suggestion, also possible problem

### ISSUE THREAD

**Issue by KEVAO28** [z0m8i3/abandoned-carts-opencart#11]
Good afternoon, I have a new suggestion / idea ... When an unregistered person goes to the checkout the module also filters this possible request to the obvious person who does not send the email to that person because he is not registered in the then you can not know her email. Is there any way to make this work only for people who are logged in / registered? Because this can generate a gigantic list of abandoned carts of "ghosts"

And also the portuguese translation of portugal the name of the folder should be pt-pt that is paste used by most of the translations.

**Comment by KEVAO28** [comment]
I'm using the Journal2 theme I tested in quickcheckout and default checkout and both are registering requests for "ghosts"

http://prntscr.com/ixbsvr


I thank you for the beautiful support you have been giving to this module

**Comment by z0m8i3** [comment]
Ajax Quickcheckout, right?

I believe that plugin works as so it starts logging immediately because it's asynchronous and it updates each time the focus changes.

It's really not a good idea to keep these obsolete records around, bloating your database up; they're useless records and should be purged periodically to free up space & prevent bloat.  The way that extension functions, its required behavior unfortunately.  But it can be rectified.

The question is, when/where is the best place to cleanup?  This isn't necessarily a "problem" with the abandoned carts extension; but the existence of the bloat does make its usability a bit more cluttered.

I am happy to work on a cleanup extension, as I know you and others would find it useful and it would not take a lot of time!

I have no eta for completion (I have not started it yet) and there are other scripts I am working on at the moment so as soon as I get free time I can definitely put something together to take care of this situation.

My thoughts:
- I can devise a script that, upon login to admin, goes through and purges these ghost orders once they're a certain age (like once the record has aged either a day or an hour, for example)

- I don't recommend immediate deletion, because then you'd run the risk of purging a pokey customer who's hovering on the checkout page at just the right time when you happen to login (which would trigger the deletions)

What would be your expected behavior?  I'd like to make this as useful as possible for you, since you came up with the suggestion, essentially.

**Comment by KEVAO28** [comment]
Yes, it's Ajax quickcheckout.

My suggestion is a button next to the button we sent the email, a simple button with "x" written delete selected records, I think this would be a good option so the administrator would delete whatever you want just by selecting what you want, sorry I make you read my bad english hahaha

- But among the options mentioned by you I believe that the best would be the script that after the administrator login and pass and eliminate the phantom requests when they are a certain age

If these scripts you are working on are from opencart I would be happy to test and report a bug or have suggestions / ideas for them. I want you to thrive on everything you develop!

**Comment by z0m8i3** [comment]
@KEVAO28 [Purge Ghost Orders](https://github.com/z0m8i3/purge-ghost-orders-opencart) has been completed. :smile:
I will also make adjustments to Abandoned Carts to ignore these new orders, so if the records don't meet the deletion threshold yet, they won't gunk up the stats for Onepage checkout users.
