### ISSUE TITLE
Regarding Arabic language files

### ISSUE THREAD

**Issue by 7oda187** [z0m8i3/abandoned-carts-opencart#6]
Dear Angela,
I was checking the new version Arabic files i have found a lot of wrong translations. and don't make any since, i have modified and correct it. if you like i have attached updated one.

[ar.zip](https://github.com/z0m8i3/abandoned-carts-opencart/files/1844037/ar.zip)

**Comment by 7oda187** [comment]
Dear,
I don't know how to make pull request, but if you can check it from your side you will find the mistakes the the corrections of it.

**Comment by z0m8i3** [comment]
I do not speak Arabic, so I am reliant on translators for the extra languages. :smile: 

To create a pull request
* [fork this repository](https://github.com/z0m8i3/abandoned-carts-opencart) (the fork button is in the just beneath your avatar)
* This will copy the repository to your Github account.  You can then navigate through the source code & make changes.
* Once you are ready to submit your changes, [submit a pull request](https://help.github.com/articles/creating-a-pull-request-from-a-fork/) - this button is typically available on the main page of *your* repository

For a number of changes like this, I prefer the pull request because it can be automatically merged into the codebase without affecting the code around it.  For new languages, zips are fine because nothing will be affected by its introduction; if a language already exists, then it becomes difficult to update it without merging.

**Comment by 7oda187** [comment]
Thank you for the guide.

I have create the pull request.
